version: "3.8"
services:
  database:
    container_name: dealership-mysql
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PWD}
      - MYSQL_DATABASE=${MYSQL_DEFAULT_DB}
